# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Apache2-PageKit
version:      2.14
version_from: lib/Apache2/PageKit.pm
installdirs:  site
requires:
    Apache2::URI:                  0
    Apache2::Util:                 0
    Apache::SessionX:              0
    Apache::Test:                  1.05
    Compress::Zlib:                0
    Data::FormValidator:           0
    Encode:                        0
    HTML::Clean:                   0
    HTML::FillInForm:              0.12
    HTML::Template:                2.2
    HTML::Template::XPath:         0.1
    mod_perl2:                     2
    XML::LibXML:                   1.53

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
